### ISSUE TITLE
How to use with a frontend?

### ISSUE THREAD

**Issue by ilrein** [bogeychan/elysia-oauth2#2]
Currently all the docs use a html rendered page. How can you configure the redirect uri to send to another dedicated frontend app?

**Comment by bogeychan** [comment]
Hi 👋

you can use the `redirectTo` option for that purpose:

https://github.com/bogeychan/elysia-oauth2/blob/766867ee1de9e2582b3faa74ef92f6685dcfd569/src/index.ts#L119-L124

by either specifying a path on the server:

```ts
oauth2({
  redirectTo: '/myRedirect',
  // ...
});
```

or an absolute url to another server:

```ts
oauth2({
  redirectTo: 'http://localhost:8080/',
  // ...
});
```

If you need to redirect on the server first (to run some code), you can delay the destination redirection as follows:

```ts
const auth = oauth2({
  redirectTo: '/myRedirect',
  // ...
});

app
  .use(auth)
  .get('/myRedirect', (ctx) => {
    // handle custom redirect on server
    ctx.set.redirect = 'http://localhost:8080/';
  })
```

**Comment by ilrein** [comment]
Hey @bogeychan 👋 

Thanks for this awesome library!

I ended up figuring out this part already lol!

But I was curious: how to handle sharing the token? Should you store the token in memory? Or put it into a database, then return that with the 2nd redirect?
