### ISSUE TITLE
[BUG] Discord scope join

### ISSUE THREAD

**Issue by bombitmanbomb** [bogeychan/elysia-oauth2#3]
In discord OAuth, scopes are expected to be Space separated (%20)
Current implementation uses Comma separation (%2C) exclusively and results in scope error response if multiple scopes are used.

**Comment by bogeychan** [comment]
Hi 👋

Thanks for your feedback. should be fixed in `0.0.12`.

**Comment by bombitmanbomb** [comment]
Much thanks!

**Comment by bombitmanbomb** [comment]
Checked the change, Would that not break other providers?

Discord is a bit.. special

**Comment by bogeychan** [comment]
no, using spaces complies with the specification: [RFC6749 Section 3.3](https://www.rfc-editor.org/rfc/rfc6749#section-3.3).

This can be found in most provider docs too. I only used the library with Reddit so far. Reddit allows both space- and comma separated scopes
